In [32]:
import numpy as np
x=np.eye(5,)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
tr=np.empty((5,4))
print(tr)

[[1.23802473e-311 6.12641401e-322 0.00000000e+000 0.00000000e+000]
 [1.42417900e-306 1.15998412e-028 4.31603868e-080 1.94919985e-153]
 [1.35717430e+131 9.72826561e-072 8.04882561e-096 1.39804329e-076]
 [1.39803697e-076 4.08598363e-033 1.08539816e-071 2.59050082e-144]
 [2.86530729e+161 2.59050167e-144 4.82412328e+228 1.04718130e-142]]


In [33]:
x.astype('int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# **sequential array**

In [36]:
print(np.arange(start=1,stop=10,step=2))

[1 3 5 7 9]


In [38]:
print(np.arange(0,10,2))

[0 2 4 6 8]


# **creating linearly spaced array**

In [40]:
print(np.linspace(start=1,stop=10,num=5,dtype='int'))

[ 1  3  5  7 10]


In [1]:
import numpy as np 


# **Multidimentional numpy array**


In [5]:
 """Mathematica objects:
 scalar: 4 or 4.5(0 D)
 Vector:[1,2,4,5](1-D)
 matrix: [[1,2,342],
          [2,4,5]](2-D)
 tensor: an x-dimentional array where x>2         
          """
scalar =np.array(48)
vector= np.array([1,4,543,56])
matrix=np.array(
    [[1,4,5],
     [2,4,5],
     [5,6,2]
    ])
print('scalar',scalar)
print('vector',vector)
print('matrix',matrix)

scalar 48
vector [  1   4 543  56]
matrix [[1 4 5]
 [2 4 5]
 [5 6 2]]


In [8]:
print('dimenstion of scalar',scalar.ndim)
print('dimenstion of vector',vector.ndim)
print('dimenstion of matrix',matrix.ndim)

dimenstion of scalar 0
dimenstion of vector 1
dimenstion of matrix 2


In [10]:
"""Numpy indexing 
    non-negative indexing(0,1,2,3,4,N-1)
    negative indexing(-1,-2,-3,....)
    """
nps=np.array([1,2,43,4,6])
print(nps[1])
print(nps[-1])


2
6


# **"""numpy slicing"""**


In [13]:
s=[1,2,4,5,6,673]
print(s[1:4:1])


[2, 4, 5]


In [23]:
two_d_array=np.array([[1,14,143,12],
          [3,4,1,51],
          [35,2,5,1]])
print(two_d_array)
print(two_d_array[0:2:1,1:3])

[[  1  14 143  12]
 [  3   4   1  51]
 [ 35   2   5   1]]
[[ 14 143]
 [  4   1]]


# **Numpy Reshape**

In [45]:
two_d_array=np.array([[1,14,143,12],
          [3,4,1,51],
          [35,2,5,1]])

reshape_2D_array=two_d_array.reshape(4,3)
print(two_d_array.shape)
print(reshape_2D_array.shape)
print(two_d_array)
print(reshape_2D_array)

(3, 4)
(4, 3)
[[  1  14 143  12]
 [  3   4   1  51]
 [ 35   2   5   1]]
[[  1  14 143]
 [ 12   3   4]
 [  1  51  35]
 [  2   5   1]]


In [34]:
my_np_array=np.zeros(shape=(3,4,2,2))
print(my_np_array)

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


# **Numpy Filtering**

In [5]:
my_1D_array=np.array(
    [1,2,3]
)
filtered_mask=[True,False,True]
filtered_array=my_1D_array[filtered_mask]
print(filtered_array)

[1 3]


In [63]:
"""Vectorization"""
my_1D_array=np.array(
    [1,2,3,4,5]
)
my_1D_array%2==0
print(my_1D_array%2==1)
print(my_1D_array[my_1D_array%2==1])

[ True False  True False  True]
[1 3 5]


In [64]:
my_1D_array +=5
my_1D_array

array([ 6,  7,  8,  9, 10])

# **broadcasting vectorization**

**Converting a lower shape into higher shape**


In [2]:
'previous batch class 17 time:4.06pm'
"""Broadcasting
converting a lower shape into higher shape for vectorization

condition: requires that the arrays involved in the operation either have the same size in each dimension or that one of the arrays has a size of 1 in that dimension.

For example: (6, 7, 7) and (6,)

Step 1: Convert the lower dimensional object to the same dimension of the higher dimensional object by replacing the empty dimensions with 1
(6,) => (6, 1, 1)

Step 2. Verify compatibility of the broadcasting
(6, 7, 7)
(6, 1, 1) So this shape can be broadcasted.

For example, (6, 31 8) and (6, 2)
(6, 2) => (6, 2, 1) will provie error
"""
import numpy as np
w=np.array([1,2])
x=np.array([
    [22,4],
    [34,1],
    [234,1],
    [2,45]
])
print(w.shape)
print(x.shape)
print(w*x)

(2,)
(4, 2)
[[ 22   8]
 [ 34   2]
 [234   2]
 [  2  90]]


In [11]:
xy=np.array([[4,41],
             [1,4],
             [43,4]])
print(x*xy)

ValueError: operands could not be broadcast together with shapes (4,2) (3,2) 

In [12]:
print(x.ndim)
print(x.shape)

2
(4, 2)


# **numpy axis**

In [23]:
 """
    Numpy Axis
    First dimension: axis=0
    Second dimension: axis=1
    Third dimension: axis=2
    ...
    Nth dimension: axis=N-1 [6, 7]"""
my_np_array=np.array(
    [[1,4,5],
     [2,5,1],
     [2,1,5]])
s=np.sum(my_np_array,axis=1)
print(s)

[10  8  8]


In [31]:
c = np.array([[[1, 2,1],
               [3, 4,5]],
              
              [[5, 6,5],
               [7, 8,5]]])
y=np.sum(c,axis=1)
z=np.sum(c,axis=2)
j=np.sum(c,axis=0)
print(c.shape)
print('sum of rows',y)
print('sum of collumns',z)
print('sum of multidimensions',j)

(2, 2, 3)
sum of rows [[ 4  6  6]
 [12 14 10]]
sum of collumns [[ 4 12]
 [16 20]]
sum of multidimensions [[ 6  8  6]
 [10 12 10]]


In [32]:
print(y.ndim)

2


# **Numpy Random**

In [47]:
print(np.random.randint(5))
print(np.random.randint(100))

1
54


In [6]:
x=(np.random.randint(100,size=(5,2)))
print(x)

[[92 98]
 [12 25]
 [65 24]
 [35  9]
 [98  2]]


In [10]:
"""shuffle"""
np.random.shuffle(x)
print(x)

[[92 98]
 [98  2]
 [35  9]
 [12 25]
 [65 24]]


In [18]:
"""sorting"""
probabilities =np.array([19,41,5,6,7])
probabilities_sorted=np.sort(probabilities)
print(probabilities_sorted)

"""Reversed Sorted"""
probabilities_reversed_sorted=np.sort(probabilities)[::-1]
print(probabilities_reversed_sorted)

[ 5  6  7 19 41]
[41 19  7  6  5]


In [19]:
"""Argmax and Argmin"""
index_max=np.argmax(probabilities)
print(index_max)

index_min=np.argmin(probabilities)
print(index_min)

1
2


In [24]:
"""array_split"""
my_np_array=np.array([1,4,2,2,5,7])
new_np_array=np.split(
    my_np_array,
    indices_or_sections=3)
print(new_np_array)


[array([1, 4]), array([2, 2]), array([5, 7])]
