# **PdfReader()**

In [1]:
!pip install pypdf

In [2]:
from pypdf import PdfReader 
pdf=PdfReader('doc.pdf')

In [3]:
len(pdf.pages)

1

In [4]:
page=pdf.pages[0]
page.extract_text()

'CHITTAGONG UNIVERSITY OF ENGINEERING & TECHNOLOGY\n                CHITTAGONG - 4349\nCOURSE REGISTRATION FORM\nSTUDENT NO 1 9 0 2 0 7 8\n    YEAR    DEPT.  ROLL NO. \nSTUDENT NAME MUNTASIR RAHMAN SAIKAT\nDEPARTMENT EEE LEVEL 4 TERM 1 SESSION 2022-2023\nNAME OF THE HALL BBH\nCOURSE NO COURSE TITLE CR.HOURS REMARKS\nEEE 431 ADVANCE COMMUNICATION ENGINEERING 3.00 regular\nEEE 432 ADVANCE COMMUNICATION ENGINEERING SESSIONAL 0.75 regular\nEEE 400 PROJECT/THESIS 0.75 regular\nEEE 471 POWER SESTEM ANALYSIS 3.00 regular\nEEE 473 TELECOMMUNICATION ENGINEERING 3.00 regular\nEEE 475 VLSI TECHNOLOGY 3.00 regular\nEEE 472 POWER SYSTEM ANALYSIS SESSIONAL 0.75 regular\nEEE 474 TELECOMMUNICATION ENGINEERING SESSIONAL 1.5 regular\nEEE 476 VLSI TECHNOLOGY SESSIONAL 1.5 regular\nEEE 402 INDUSTRIAL ATTACHMENT/TRAINING 0.75 regular\nCREDIT HOURS TAKEN (CURRENT SEMESTER) 18\n        1st LEVEL        2nd LEVEL        3rd LEVEL        4th LEVEL\n 1st Term 2nd Term 1st Term 2nd Term 1st Term 2nd Term 1st Ter

In [5]:
!pip install pypdf2

In [6]:
import PyPDF2

In [8]:
with open('doc.pdf','rb') as file :
    read=PyPDF2.PdfReader(file)
    first=read.pages[0].extract_text()
    print(first)
    

CHITTAGONG UNIVERSITY OF ENGINEERING & TECHNOLOGY
                CHITTAGONG - 4349
COURSE REGISTRATION FORM
STUDENT NO 1902078
    YEAR    DEPT.  ROLL NO. 
STUDENT NAME MUNTASIR RAHMAN SAIKAT
DEPARTMENT EEE LEVEL 4TERM 1SESSION 2022-2023
NAME OF THE HALL BBH
COURSE NO COURSE TITLE CR.HOURS REMARKS
EEE 431 ADVANCE COMMUNICATION ENGINEERING 3.00 regular
EEE 432 ADVANCE COMMUNICATION ENGINEERING SESSIONAL 0.75 regular
EEE 400 PROJECT/THESIS 0.75 regular
EEE 471 POWER SESTEM ANALYSIS 3.00 regular
EEE 473 TELECOMMUNICATION ENGINEERING 3.00 regular
EEE 475 VLSI TECHNOLOGY 3.00 regular
EEE 472 POWER SYSTEM ANALYSIS SESSIONAL 0.75 regular
EEE 474 TELECOMMUNICATION ENGINEERING SESSIONAL 1.5 regular
EEE 476 VLSI TECHNOLOGY SESSIONAL 1.5 regular
EEE 402 INDUSTRIAL ATTACHMENT/TRAINING 0.75 regular
CREDIT HOURS TAKEN (CURRENT SEMESTER) 18
        1st LEVEL        2nd LEVEL        3rd LEVEL        4th LEVEL
 1st Term 2nd Term 1st Term 2nd Term 1st Term 2nd Term 1st Term 2nd Term 
CREDIT HOUR COMPLE

In [20]:
import PyPDF2
with open('Steam Power Plant full.pdf','rb') as file:
    pdf=PyPDF2.PdfReader(file)
    read=pdf.pages[14].extract_text()
    print(read)

Art. 3.1.1. Power Station Design
15Power station design requires wide experience .A
satisfactory design ofthefollowing steps :
vii.Design ofcooling system
viii.Design ofpiping system tocarry steam and
water
ix.Selection ofelectrical generator
x.Design and control ofinstruments
xi.Design oflayout ofpower station



In [21]:
import PyPDF2
with open('Steam Power Plant full.pdf','rb') as file:
    pdf=PyPDF2.PdfReader(file)
    for page in pdf.pages:
        x=page.extract_text()
        print(x)
        print('\n')

Steam Power Plant
Course Title: Power Plant Engineering
Course No.: EEE -481
1Presented by -
Sancoy Barua
Assistant Professor,
Dept. of EEE, CUETCUET
BANGLADESH



STEAM POWER PLANT
Contents:
1.   Working principle of steam 
power plant.
2.   Purpose of draught.
3.   Types of draught.
4.   Economizer.
5.   Advantage of economizer.
6.   Air pre -heater.
7.   Types of air pre -heater.
8.   Super Heater.
9.   Type of Super Heater.
10.  Advantages of Super -heater .
2
11. Feed water Treatment. 
12. PH value of water.
13.  Stem condenser.
14. Feed water Heaters.
15. Types of steam condenser.
16. Advantages disadvantages of a 
source condenser.
17. Types of cooling Tower.
18. Factors of cooling Tower.
19. Maintenance of cooling Tower


References
1.‘Power Plant 
Engineering’ –by 
G.R. NagpalChapter 3: Steam Power Plant
3


Art.3.0:Introduction
Steam isanimportant medium ofproducing mechanical energy .
Hasadvantage asitcanberaised from water ,which isabundant .
Does notreact somuch with t

# **Generator**

In [12]:
lists=[10,23,34,5,234]
def data_generator(data):# Creating generator function 
    for i in data:
        yield i #yield er pore ja ase setai holo output

gen=data_generator(lists)#creating generator
for j in gen:
    print(j,end=' ')
        

10 23 34 5 234 

In [88]:
def number_generator():
    for i in range(10**6):
        yield i  # Generates one number at a time

gens = number_generator()  # Generator object created
print(next(gens))

0


In [90]:
print(next(gens))

1


In [91]:
type(gens)

generator

In [92]:
import sys
sys.getsizeof(gens)

192

In [84]:
import PyPDF2
def read_file(doc):
    with open(doc,'rb') as file :
        for line in file:
            yield line  # Returns one line at a time

gen = read_file("Steam Power Plant full.pdf")

print(next(gen)) # Reads and prints the first line
print('\n')
print(next(gen))
print(next(gen))
print(next(gen))
print(next(gen))# Reads and p

b'%PDF-1.5\r\n'


b'%\xb5\xb5\xb5\xb5\r\n'
b'1 0 obj\r\n'
b'<</Type/Catalog/Pages 2 0 R/Lang(bn-BD) /StructTreeRoot 654 0 R/MarkInfo<</Marked true>>>>\r\n'
b'endobj\r\n'


In [86]:
import PyPDF2

def read_pdf_text(doc):
    with open(doc, 'rb') as file:
        pdf = PyPDF2.PdfReader(file)  # Correct way to open a PDF in PyPDF2
        for page in pdf.pages:  # Loop through each page
            yield page.extract_text()  # Extract text from each page

# Create a generator
gen = read_pdf_text("Steam Power Plant full.pdf")

# Read and print extracted text
print(next(gen))  # Reads text from the first page
print('\n')
print(next(gen))  # Reads text from the second page

AttributeError: 'NameObject' object has no attribute 'extract_text'

In [93]:
sys.getsizeof(gen)

240

# **Generator with Yield**

In [97]:
def even_number():
    num=0
    while True:
        yield num
        num+=2

e=even_number()
for _ in range(5):
    print(next(e))

0
2
4
6
8


In [106]:
sys.getsizeof(e)

184

# **Generator without yield**
gen = (x*x for x in range(5))  #note that: this is not list .Rather this generator because here parenthesis is used instead of third brackets

In [102]:
even=(i for i in range(9) if i%2==0) #note that: this is not list .Rather this generator because here parenthesis is used instead of third brackets

In [103]:
even

<generator object <genexpr> at 0x000002AA8B9FCAD0>

In [104]:
for s in even:
    print(s)

0
2
4
6
8


In [105]:
sys.getsizeof(even)

200

In [26]:
my_string ='How,are,you,doing'
my_list=my_string.split(",")
print(my_list)
new_string= ' '.join(my_list)
print(new_string)

['How', 'are', 'you', 'doing']
How are you doing


# **Calculator** 

In [8]:
num1=float(input('enter the first number'))
op=input('Enter the operation')
num2=float(input('Enter the 2nd number'))
if op=='+':
   print(num1+num2)
elif op=='-':
     print(num1-num2)
elif op=='*':
    print(num1*num2)
elif op=='/':
    print(num1/num2)
else :
    print('Invalid operation')


enter the first number 23
Enter the operation /
Enter the 2nd number 21


1.0952380952380953


# **Guessing Game**

In [27]:
secret_word='giraffe'
guess=" "
print('Your guessing limit is 5')
for i in range(6):
    if i==5:
        print('sorry you have crossed the guessing limit')
    else:
         guess=input()
         if guess==secret_word:
            print('Congratulations! You have guessed it correct')
            break
         else:
              print('wrong guess')
    
   


        
    
    
  





        
    

Your guessing limit is 5


 muntasir 


wrong guess


 saikat


wrong guess


 talal


wrong guess


 talha


wrong guess


 giraffe


Congratulations! You have guessed it correct


# **Guessing Game using While loop**

In [20]:

guess=" "
secret='Istiaq'
guess_number=5
count=0
out_of_limit=False
while(guess!=secret and not out_of_limit):
    guess=input()
    count+=1
    if count==guess_number:
        out_of_limit=True
if out_of_limit:
    print('Sorry You are out of guess limit')
else:
    print('Congratulations you have guessed correct')
    

 s
 s
 s
 s
 s


Sorry You are out of guess limit


In [4]:
'''ddff dlkjkj
df
''' #multiple line comments

'ddff dlkjkj\ndf\n'

# **Try and Except method**

In [23]:
    
""" except Exception as e:
    print('error',type(e).__name__) 
    """
try:
    value=10

    number=int(input('Please, Enter the number:'))

except ValueError:
      print('Invalid input')
except ZeroDivisionError:
    print('divided by zero')


Please, Enter the number: fs


Invalid input


In [6]:
try:    
    x=int(input('Enter the range for prime numbers'))
    y=print('The prime numbers are')
    count=0
    for i in range(x+1):
        if i>1:
            Is_prime=True
            for j in range(2,int(i**0.5)+1):
                if i%j==0:
                    Is_prime=False
            if Is_prime:
                print(i)
                count+=1
    print(f'Total count={count}')

except ValueError:
      print('Invalid input')
except ZeroDivisionError:
    print('divided by zero')


     


Enter the range for prime numbers 20


The prime numbers are
2
3
5
7
11
13
17
19
Total count=8


In [14]:
x=int(input('Enter the range of prime numbers'))
for i in range(x+1):
    if i>1:
        is_prime=True
        for j in range(2,int(i**0.5)+1):
            if i%j==0:
               is_prime=False
    if is_prime:
            print(i)




Enter the range of prime numbers 101


0
1
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101


# **Use of Datetime**

In [2]:
from datetime import datetime,timedelta
print(datetime.now()-timedelta(days=2))


2025-08-27 18:10:45.234283


In [1]:
import numpy as np 
np.__version__


'1.26.4'

In [3]:
lisst=[231,14,1,3,6,7]
array=np.array(lisst)
print(array)

[231  14   1   3   6   7]


In [8]:
array.shape


(6,)

In [27]:
import numpy as np 
x=np.zeros((5,5),dtype='int')
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [29]:
y=np.full((6,),fill_value=15)
print(y)

[15 15 15 15 15 15]
