In [2]:
import numpy as np


In [2]:
n=[1,4,1,14]

In [7]:
print(n)

[1, 4, 1, 14]


In [6]:
a=np.array([1,2,3,41])
print(a)

[ 1  2  3 41]


In [10]:
print(a[:-2])

[1 2]


In [18]:
ap=np.array([[1,2,3,1],
            [34,34,52,2],
            [21,1,4,5]
           ])
print(ap.shape)

(3, 4)


In [20]:
y=np.array([
    [[1,3,4,1],
    [13,2,13,2],
    [4,4,11,34]],
    [[2,1,41,1],
    [231,2,1,4],
    [1,3,1,1]]
])
    

In [25]:
print(y.shape)

(2, 3, 4)


In [27]:
print(y.ndim)
print(ap.ndim)

3
2


In [28]:
print(y.size)

24


In [29]:
print(y.dtype)

int32


In [6]:
a=np.full((2,3,4),9)
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [8]:
a=np.zeros((2,5,2))
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [10]:
a=np.empty((2,3,2))
print(a)

[[[1.90979621e-313 1.90979621e-313]
  [1.90979621e-313 1.90979621e-313]
  [1.90979621e-313 1.90979621e-313]]

 [[1.90979621e-313 1.90979621e-313]
  [1.90979621e-313 1.90979621e-313]
  [1.90979621e-313 1.90979621e-313]]]


In [14]:
x_values=np.arange(0,1000,5)# here 5 is a step size
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [17]:
y_values=np.linspace(0,1000,3)# means I want 3 numbers in btween zero and 1000
print(y_values)

[   0.  500. 1000.]


In [18]:
print(np.isnan(np.nan))

True


In [19]:
print(np.isinf(np.inf))

True


In [23]:
print(np.sqrt(-1))

nan


C:\Users\User\AppData\Local\Temp\ipykernel_5924\267541580.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


In [27]:
print(np.array([10])/0)

[inf]


C:\Users\User\AppData\Local\Temp\ipykernel_5924\500388721.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


In [29]:
l1=[1,3,34,1,2]
l2=[1,21,41,4,1]
a1=np.array(l1)
a2=np.array(l2)
print('list multiplication:')
print(l1*4)
print('array multiplication:')
print(a1*4)

list multiplication:
[1, 3, 34, 1, 2, 1, 3, 34, 1, 2, 1, 3, 34, 1, 2, 1, 3, 34, 1, 2]
array multiplication:
[  4  12 136   4   8]


In [30]:
print(l1+l2)
print(a1+a2)

[1, 3, 34, 1, 2, 1, 21, 41, 4, 1]
[ 2 24 75  5  3]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [35]:
b1=np.array([[1,2,4],
            [32,211,1],
            [2,4,32]])
b2=np.array([[23,2,1],
             [3,1,12],
             [34,12,5]])
c=b1*b2
print(c)

[[ 23   4   4]
 [ 96 211  12]
 [ 68  48 160]]


In [36]:
print(np.sqrt(c))

[[ 4.79583152  2.          2.        ]
 [ 9.79795897 14.52583905  3.46410162]
 [ 8.24621125  6.92820323 12.64911064]]


In [100]:
z=np.append(b1,[3,4,5])

In [101]:
z

array([  1,   2,   4,  32, 211,   1,   2,   4,  32,   3,   4,   5])

In [102]:
z=np.insert(z,1,[233,442])
z

array([  1, 233, 442,   2,   4,  32, 211,   1,   2,   4,  32,   3,   4,
         5])

# **Use of delete**

In [103]:
print(np.delete(z,2))

[  1 233   2   4  32 211   1   2   4  32   3   4   5]


In [49]:
b1

array([[  1,   2,   4],
       [ 32, 211,   1],
       [  2,   4,  32]])

In [56]:
print(np.delete(b1,1,1)) # np.delete(array, obj, axis)

[[ 1  4]
 [32  1]
 [ 2 32]]


In [6]:
a=np.array([[2,1,1,32,1],
            [12,11,23,1,4],
            [13,34,12,41,43],
            [32,41,4,2,5]])
print(a.shape)
print(a.reshape(5,4))
print(a.reshape(10,2,1))
                

(4, 5)
[[ 2  1  1 32]
 [ 1 12 11 23]
 [ 1  4 13 34]
 [12 41 43 32]
 [41  4  2  5]]
[[[ 2]
  [ 1]]

 [[ 1]
  [32]]

 [[ 1]
  [12]]

 [[11]
  [23]]

 [[ 1]
  [ 4]]

 [[13]
  [34]]

 [[12]
  [41]]

 [[43]
  [32]]

 [[41]
  [ 4]]

 [[ 2]
  [ 5]]]


In [90]:
b=a
b

array([[ 2,  1,  1, 32,  1],
       [12, 11, 23,  1,  4],
       [13, 34, 12, 41, 43],
       [32, 41,  4,  2,  5]])

# **Use of ravel and flatten**

In [82]:
print(a.flatten())
print(b.ravel())

[ 2  1  1 32  1 12 11 23  1  4 13 34 12 41 43 32 41  4  2  5]
[ 2  1  1 32  1 12 11 23  1  4 13 34 12 41 43 32 41  4  2  5]


In [91]:
# flatten doesn't change the original array value 
var1=a.flatten()
var1[2]=100

print(var1)
print(a)# main array doesn't change


[  2   1 100  32   1  12  11  23   1   4  13  34  12  41  43  32  41   4
   2   5]
[[ 2  1  1 32  1]
 [12 11 23  1  4]
 [13 34 12 41 43]
 [32 41  4  2  5]]


In [92]:
# ravel does change the original array value 
var2=b.ravel()
var2[2]=100
print(var2)
print(b)#main array does change

[  2   1 100  32   1  12  11  23   1   4  13  34  12  41  43  32  41   4
   2   5]
[[  2   1 100  32   1]
 [ 12  11  23   1   4]
 [ 13  34  12  41  43]
 [ 32  41   4   2   5]]


# **Transposing**

In [96]:
print(a)
print('\n',a.transpose())

[[  2   1 100  32   1]
 [ 12  11  23   1   4]
 [ 13  34  12  41  43]
 [ 32  41   4   2   5]]

 [[  2  12  13  32]
 [  1  11  34  41]
 [100  23  12   4]
 [ 32   1  41   2]
 [  1   4  43   5]]


In [107]:
print(a)
print('\n',a.T)

[[  2   1 100  32   1]
 [ 12  11  23   1   4]
 [ 13  34  12  41  43]
 [ 32  41   4   2   5]]

 [[  2  12  13  32]
 [  1  11  34  41]
 [100  23  12   4]
 [ 32   1  41   2]
 [  1   4  43   5]]


In [110]:
print(a)
print('\n',a.swapaxes(0,1))

[[  2   1 100  32   1]
 [ 12  11  23   1   4]
 [ 13  34  12  41  43]
 [ 32  41   4   2   5]]

 [[  2  12  13  32]
 [  1  11  34  41]
 [100  23  12   4]
 [ 32   1  41   2]
 [  1   4  43   5]]


# **concatenation**

In [121]:

 a1=np.array([[  2  ,12,  13,  32],
 [  1 , 11,  34,  41],
 [100  ,23 , 12,   4]])
a2=np.array([
 [ 32  ,1  ,41,   2],
 [  1   ,4  ,43  , 5]])
s=np.concatenate((a1,a2),axis=0)#np.vstack

In [122]:
s

array([[  2,  12,  13,  32],
       [  1,  11,  34,  41],
       [100,  23,  12,   4],
       [ 32,   1,  41,   2],
       [  1,   4,  43,   5]])

In [123]:

 a1=np.array([[  2  ,12,  13,  32],
 [  1 , 11,  34,  41],
])
a2=np.array([
 [ 32  ,1  ,41,   2],
 [  1   ,4  ,43  , 5]])
print(np.concatenate((a1,a2),axis=1))#alternative: np.hstack


[[ 2 12 13 32 32  1 41  2]
 [ 1 11 34 41  1  4 43  5]]


# **Use of stack**

In [128]:
i=np.stack((a1,a2))

In [129]:
i.shape

(2, 2, 4)

In [7]:
a

array([[ 2,  1,  1, 32,  1],
       [12, 11, 23,  1,  4],
       [13, 34, 12, 41, 43],
       [32, 41,  4,  2,  5]])

In [9]:
np.split(a,4,axis=0)

[array([[ 2,  1,  1, 32,  1]]),
 array([[12, 11, 23,  1,  4]]),
 array([[13, 34, 12, 41, 43]]),
 array([[32, 41,  4,  2,  5]])]

In [14]:
print(a.min())
print(a.mean())
print(a.max())
print(a.std())
print(a.sum())
print(np.median(a))
print(np.max(a))

1
15.75
43
15.214713273670325
315
11.5
43


In [26]:
print(np.random.randint(3,100))

46


In [29]:
print(np.random.randint(2,size=(5,2,5)))

[[[1 1 1 0 1]
  [0 0 0 0 1]]

 [[0 1 1 1 0]
  [0 0 0 0 0]]

 [[1 0 0 1 1]
  [1 0 0 1 0]]

 [[1 1 0 0 1]
  [0 1 0 0 0]]

 [[1 1 1 1 1]
  [0 1 0 1 0]]]


In [11]:
numbers=np.random.binomial(10,p=0.5,size=(5,10))
print(numbers)

[[4 6 2 4 4 5 5 7 8 4]
 [6 6 6 8 5 4 3 6 6 5]
 [8 6 5 4 3 3 7 3 2 3]
 [8 5 6 6 2 6 8 4 4 5]
 [6 3 4 4 4 8 4 7 3 6]]


In [14]:
numbers=np.random.normal(loc=170,scale=15,size=(5,10))
print(numbers)

[[174.83612565 166.95059711 168.02881845 158.92507432 168.06514766
  183.12933183 165.23482617 154.32987282 186.79768452 161.81872113]
 [169.42868138 144.3078812  160.94052497 191.47689457 150.48418427
  183.02762118 172.91479141 156.27003577 166.20692559 178.81923216]
 [158.05337682 207.12932182 179.96259354 171.19096135 164.97844045
  188.06490792 170.01277373 166.98864115 149.3910332  175.64409467]
 [151.08856139 168.50863166 166.70262529 156.54373481 152.25966203
  151.31860436 174.59958636 174.4104355  160.82012848 195.49913163]
 [151.1966879  165.29309816 169.44452651 148.06621494 199.92662362
  157.22254383 183.33285078 186.25226854 169.55344529 205.02010587]]


In [16]:
numbers=np.random.choice([10,20,30,40,50],size=(5,10))
print(numbers)

[[30 40 20 40 40 10 10 40 30 10]
 [40 30 40 30 40 40 50 20 30 20]
 [30 30 20 30 10 30 30 20 10 10]
 [10 10 30 50 20 50 50 10 20 40]
 [30 30 50 40 10 20 30 30 20 20]]


# **Exporting and importing numpy arrays**

**npy file**

In [19]:
a=np.array([[1,2,4,5,6],
           [1,32,1,1,3],
           [43,1,132,1,3]])
np.save("myarray.npy",a)


In [20]:
k=np.load("myarray.npy")
print(k)

[[  1   2   4   5   6]
 [  1  32   1   1   3]
 [ 43   1 132   1   3]]


**csv file**

In [23]:
np.savetxt('myarray.csv',a,delimiter=',')

In [28]:
f=np.loadtxt('myarray.csv',delimiter=',')
print(f)

[[  1.   2.   4.   5.   6.]
 [  1.  32.   1.   1.   3.]
 [ 43.   1. 132.   1.   3.]]


In [2]:
a=[1,2,3]
print(a[13:])

[]


In [5]:
a=255
b=255
print(a is b)
a=3
b=3
print(a is b)

True
True


In [11]:
def weird_function(x=[]):
    x.append(1)
    return x



In [12]:
print(weird_function())
print(weird_function())
print(weird_function())

[1]
[1, 1]
[1, 1, 1]


In [25]:
a=[1,2,3]
b=a
b.append(4)

In [20]:
print(b)

None
