In [3]:

import torch
import numpy as np
print(np.random.randint(1,10,3))

[8 8 1]


In [1]:
import torch.nn as nn
class Perceptron(nn.Module):
    def __init__(self,input_size):
        super(Perceptron,self).__init__()
        self.input_size=input_size
        self.weights=nn.Parameter(
            torch.randn(self.input_size)
        )
        self.bias=nn.Parameter(
            torch.zeros(1)
        )
    def forward(self,x):
        z=x@ self.weights+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred




In [34]:
model=Perceptron(input_size=3)
torch.manual_seed(43)
x=torch.randn(3)
y_pred=model(x)
print(y_pred)

tensor([0.1309], grad_fn=<SigmoidBackward0>)


In [12]:
print(torch.randn(2))

tensor([ 0.9988, -0.7986])


In [31]:
print(*model.parameters())

Parameter containing:
tensor([ 1.4788,  1.1918, -0.1446], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [35]:
X=torch.Tensor(
    [
        [0.0,0.0,0.0],
        [1.0,0.0,0.0],
        [0.0,1.0,0.0],
        [1.0,1.0,1.0],
    ]
)
Y=torch.Tensor(
    [
        [0.0],
        [0.0],
        [0.0],
        [1.0]
    ]
)

In [36]:
"""Cost Function"""
criterion=nn.BCELoss()
"""Optimizer"""
optimizer=torch.optim.Adam(
    model.parameters(),
    lr=0.001,
)


In [38]:
y_pred=model(X)

In [39]:
y_pred

tensor([0.5000, 0.8144, 0.7671, 0.9259], grad_fn=<SigmoidBackward0>)

In [40]:
print(*model.parameters())

Parameter containing:
tensor([ 1.4788,  1.1918, -0.1446], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [41]:
y_pred.shape

torch.Size([4])

In [45]:
y_pred=y_pred.unsqueeze(1)
y_pred

tensor([[[0.5000]],

        [[0.8144]],

        [[0.7671]],

        [[0.9259]]], grad_fn=<UnsqueezeBackward0>)

In [46]:
y_pred.shape

torch.Size([4, 1, 1])

In [49]:
def train_model(model,epochs):
    for epoch in range(epochs):
        y_pred=model(X)
        loss=criterion(y_pred.unsqueeze(1),Y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if epoch%1000==0:
            print(f"epoch: {epoch}, loss: {loss}")

In [55]:
train_model(model=model,epochs=100000)

epoch: 0, loss: 0.011541906744241714
epoch: 1000, loss: 0.008031554520130157
epoch: 2000, loss: 0.005595778580754995
epoch: 3000, loss: 0.003902543568983674
epoch: 4000, loss: 0.0027236794121563435
epoch: 5000, loss: 0.001902015064842999
epoch: 6000, loss: 0.001328838407061994
epoch: 7000, loss: 0.0009287017164751887
epoch: 8000, loss: 0.0006492160609923303
epoch: 9000, loss: 0.00045393803156912327
epoch: 10000, loss: 0.0003174403100274503
epoch: 11000, loss: 0.00022202882973942906
epoch: 12000, loss: 0.00015529034135397524
epoch: 13000, loss: 0.00010862886847462505
epoch: 14000, loss: 7.596852083224803e-05
epoch: 15000, loss: 5.3149633458815515e-05
epoch: 16000, loss: 3.718948210007511e-05
epoch: 17000, loss: 2.6006586267612875e-05
epoch: 18000, loss: 1.8212662325822748e-05
epoch: 19000, loss: 1.273593989026267e-05
epoch: 20000, loss: 8.901062756194733e-06
epoch: 21000, loss: 6.246429165912559e-06
epoch: 22000, loss: 4.367265319160651e-06
epoch: 23000, loss: 3.044718141609337e-06
epoc

In [59]:
def predict(model,x):
    """Model Evaluation Mode"""
    model.eval()
    with torch.no_grad():
        test_output=model(x)
    return test_output
predict(model,X)

tensor([1.3298e-12, 9.1104e-10, 9.1104e-10, 1.0000e+00])

In [60]:
model.state_dict()

OrderedDict([('weights', tensor([ 6.5295,  6.5295, 30.9256])),
             ('bias', tensor([-27.3460]))])

In [61]:
torch.save(model.state_dict(),"model.pt")

In [62]:
"""Loading the model using these saved parameters"""
loaded_model=Perceptron(input_size=3)
loaded_model.load_state_dict(torch.load("model.pt"))

<All keys matched successfully>

In [63]:
"""Prediction with this loaded model"""
loaded_model(X)

tensor([1.3298e-12, 9.1104e-10, 9.1104e-10, 1.0000e+00],
       grad_fn=<SigmoidBackward0>)